# Generated by Django 3.1.7 on 2021-06-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
