# Generated by Django 3.1.7 on 2021-06-20 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tic_tac_app', '0002_auto_20210620_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_for_user_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_for_user_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
